include:
- local: '/ci-pipelines/cleanup.gitlab-ci.yml'

stages:
- build
- cleanup

variables:
  PACKAGENAME: 'mainComponent'
  VERSIONCOMPONENTTOINCREMENT: '-p'
  # -M = Major (first position), -m = minor (second position), -p = patch (third position)

batch:
  stage: build
  script:
    - mkdir -p bin
    - make -f makeGeneric
    - bin/main