include:
- local: '/ci-pipelines/cleanup.gitlab-ci.yml'

variables:
  PACKAGENAME: 'main'
  VERSION: 0.0.1


stages:
- build
- upload
- download
- cleanup

cache:
  key: "%CI_PIPELINE_ID%"
  paths:
    - bin/

batch:
  stage: build
  script:
    - mkdir -p bin
    - make -f makeGeneric

upload:
  image: curlimages/curl:latest
  stage: upload
  script:
    - |
      echo "${VERSION}" > version.txt
      echo "${VERSION}" > version-${VERSION}.txt
      echo "VERSION=${VERSION}" > version.env
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file bin/main ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGENAME}/${VERSION}/${PACKAGENAME}.${VERSION}

download_test:
  image: bash:latest
  stage: download
  # The $VERSION is propagated from the previous job via dotenv files capability of Gitlab CI
  script:
    - |
      apk add wget curl
      wget --header="JOB-TOKEN: $CI_JOB_TOKEN" ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGENAME}/${VERSION}/${PACKAGENAME}.${VERSION}
    - chmod +x ${PACKAGENAME}.${VERSION}
    - ls -la
    - readlink -f ${PACKAGENAME}.${VERSION}
    - /builds/janhkrueger/cpp-tutorial-featureflags/${PACKAGENAME}.${VERSION}
