include:
- local: '/ci-pipelines/cleanup.gitlab-ci.yml'

stages:
- build
- execute
- cleanup

variables:
  PACKAGENAME: 'mainComponent'
  VERSIONCOMPONENTTOINCREMENT: '-p'
  # -M = Major (first position), -m = minor (second position), -p = patch (third position)


cache:
  key: "%CI_PIPELINE_ID%"
  paths:
    - bin/

batch:
  stage: build
  script:
    - mkdir -p bin
    - make -f makeGeneric

run:
  stage: execute
  when: on_success
  script:
    - bin/main
