include:
- local: '/ci-pipelines/cleanup.gitlab-ci.yml'

stages:
- build
- upload
- cleanup

variables:
  PACKAGENAME: 'mainComponent'

cache:
  key: "%CI_PIPELINE_ID%"
  paths:
    - bin/

batch:
  image: curlimages/curl:latest
  stage: build
  script:
    - mkdir -p bin
    - make -f makeGeneric
    - bin/main

upload:
  image: curlimages/curl:latest
  stage: upload
  script:
    - |
      VERSION=0.0.1
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file bin/main ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGENAME}/${VERSION}/${PACKAGENAME}.${VERSION}
